### ISSUE TITLE
update-notifier-common not available on Debian >= 8.0

### ISSUE THREAD

**Issue by waja** [simondeziel/custom-nagios-plugins#5]
Hi @simondeziel,

since Debian Jessie the package update-notifier-common is not available anymore. The script isn't even moved into any other package. So check_apt_upgrade isn't working there.

**Comment by simondeziel** [comment]
Hi waja, thanks for the heads up. It seems like Debian is abandoning it in favor of gnome-packagekit.

Fortunately, Ubuntu continues to ship update-notifier(-common). They are now shipping version 3.16 [1] while Debian turned version 3.14 [2] into a transition package to gnome-packagekit. Maybe the original Debian maintainer for update-notifier could be convinced to re-integrate at least update-notifier-common into Debian?

I unfortunately don't have the time to look into this myself so, please feel free to initiate the work on the Debian front.

Best regards,
Simon

1: http://packages.ubuntu.com/vivid/update-notifier-common
2: https://packages.debian.org/search?keywords=update-notifier

**Comment by simondeziel** [comment]
Now that check_apt works better than it used to, I think I'll deprecate check_apt_upgrade so closing.
